/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    'email': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateUserDto
     */
    'roles': Array<CreateUserDtoRolesEnum>;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    'authProvider': CreateUserDtoAuthProviderEnum;
}

export const CreateUserDtoRolesEnum = {
    User: 'user',
    Admin: 'admin'
} as const;

export type CreateUserDtoRolesEnum = typeof CreateUserDtoRolesEnum[keyof typeof CreateUserDtoRolesEnum];
export const CreateUserDtoAuthProviderEnum = {
    Local: 'local',
    Google: 'google'
} as const;

export type CreateUserDtoAuthProviderEnum = typeof CreateUserDtoAuthProviderEnum[keyof typeof CreateUserDtoAuthProviderEnum];


