/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GraphConfig
 */
export interface GraphConfig {
    /**
     * 
     * @type {string}
     * @memberof GraphConfig
     */
    'labelColumn'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GraphConfig
     */
    'valueColumns'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GraphConfig
     */
    'chartType'?: GraphConfigChartTypeEnum;
}

export const GraphConfigChartTypeEnum = {
    Line: 'line',
    Bar: 'bar',
    Pie: 'pie'
} as const;

export type GraphConfigChartTypeEnum = typeof GraphConfigChartTypeEnum[keyof typeof GraphConfigChartTypeEnum];


