/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GraphConfigDto
 */
export interface GraphConfigDto {
    /**
     * Column to use as label (X-axis or category)
     * @type {string}
     * @memberof GraphConfigDto
     */
    'labelColumn'?: string;
    /**
     * Columns to use as values (Y-axis)
     * @type {Array<string>}
     * @memberof GraphConfigDto
     */
    'valueColumns'?: Array<string>;
    /**
     * Chart type to use
     * @type {string}
     * @memberof GraphConfigDto
     */
    'chartType'?: GraphConfigDtoChartTypeEnum;
}

export const GraphConfigDtoChartTypeEnum = {
    Line: 'line',
    Bar: 'bar',
    Pie: 'pie'
} as const;

export type GraphConfigDtoChartTypeEnum = typeof GraphConfigDtoChartTypeEnum[keyof typeof GraphConfigDtoChartTypeEnum];


