/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GraphConfigDto } from './graph-config-dto';

/**
 * 
 * @export
 * @interface UpdateQueryDto
 */
export interface UpdateQueryDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateQueryDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateQueryDto
     */
    'query'?: string;
    /**
     * 
     * @type {GraphConfigDto}
     * @memberof UpdateQueryDto
     */
    'graphConfig'?: GraphConfigDto;
}

