/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    'email'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateUserDto
     */
    'roles'?: Array<UpdateUserDtoRolesEnum>;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    'authProvider'?: UpdateUserDtoAuthProviderEnum;
}

export const UpdateUserDtoRolesEnum = {
    User: 'user',
    Admin: 'admin'
} as const;

export type UpdateUserDtoRolesEnum = typeof UpdateUserDtoRolesEnum[keyof typeof UpdateUserDtoRolesEnum];
export const UpdateUserDtoAuthProviderEnum = {
    Local: 'local',
    Google: 'google'
} as const;

export type UpdateUserDtoAuthProviderEnum = typeof UpdateUserDtoAuthProviderEnum[keyof typeof UpdateUserDtoAuthProviderEnum];


